export type LanguageCode =
  | "hi" // Hindi
  | "bn" // Bengali
  | "ta" // Tamil
  | "te" // Telugu
  | "mr" // Marathi
  | "gu" // Gujarati
  | "kn" // Kannada
  | "ml" // Malayalam
  | "pa" // Punjabi
  | "or" // Odia
  | "as" // Assamese
  | "ur"; // Urdu

export const LANGUAGES: { code: LanguageCode; name: string; native: string }[] = [
  { code: "hi", name: "Hindi", native: "हिंदी" },
  { code: "bn", name: "Bengali", native: "বাংলা" },
  { code: "ta", name: "Tamil", native: "தமிழ்" },
  { code: "te", name: "Telugu", native: "తెలుగు" },
  { code: "mr", name: "Marathi", native: "मराठी" },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ" },
  { code: "ml", name: "Malayalam", native: "മലയാളം" },
  { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ" },
  { code: "or", name: "Odia", native: "ଓଡିଆ" },
  { code: "as", name: "Assamese", native: "অসমীয়া" },
  { code: "ur", name: "Urdu", native: "اردو" },
];

export type FieldKey =
  | "fullName"
  | "address1"
  | "address2"
  | "district"
  | "state"
  | "pincode"
  | "dob"
  | "gender"
  | "phone"
  | "email"
  | "aadhaar"
  | "pan"
  | "maritalStatus"
  | "occupation"
  | "annualIncome"
  | "declaration"
  | "signature";

export const FIELD_ORDER: FieldKey[] = [
  "fullName",
  "address1",
  "address2",
  "district",
  "state",
  "pincode",
  "dob",
  "gender",
  "phone",
  "email",
  "aadhaar",
  "pan",
  "maritalStatus",
  "occupation",
  "annualIncome",
  "declaration",
  "signature",
];

export const EN_LABELS: Record<FieldKey, string> = {
  fullName: "Full Name",
  address1: "Address Line 1",
  address2: "Address Line 2",
  district: "District",
  state: "State",
  pincode: "PIN Code",
  dob: "Date of Birth",
  gender: "Gender",
  phone: "Phone Number",
  email: "Email",
  aadhaar: "Aadhaar Number",
  pan: "PAN Number",
  maritalStatus: "Marital Status",
  occupation: "Occupation",
  annualIncome: "Annual Income",
  declaration: "Declaration",
  signature: "Signature",
};

export type Dictionary = Partial<Record<FieldKey, string>>;
export type LanguageDictionaries = Record<LanguageCode, Dictionary>;

// Curated label translations for government form vocabulary across major Indian languages.
export const LABELS: LanguageDictionaries = {
  hi: {
    fullName: "पूरा नाम",
    address1: "पता पंक्ति 1",
    address2: "पता पंक्ति 2",
    district: "जिला",
    state: "राज्य",
    pincode: "पिन कोड",
    dob: "जन्म तिथि",
    gender: "लिंग",
    phone: "फोन नंबर",
    email: "ईमेल",
    aadhaar: "आधार संख्या",
    pan: "पैन संख्या",
    maritalStatus: "वैवाहिक स्थिति",
    occupation: "व्यवसाय",
    annualIncome: "वार्षिक आय",
    declaration: "घोषणा",
    signature: "हस्ताक्षर",
  },
  bn: {
    fullName: "পূর্ণ নাম",
    address1: "ঠিকানা লাইন ১",
    address2: "ঠিকানা লাইন ২",
    district: "জেলা",
    state: "রাজ্য",
    pincode: "পিন কোড",
    dob: "জন্মতারিখ",
    gender: "লিঙ্গ",
    phone: "ফোন নম্বর",
    email: "ইমেল",
    aadhaar: "আধার নম্বর",
    pan: "প্যান নম্বর",
    maritalStatus: "বৈবাহিক অবস্থা",
    occupation: "পেশা",
    annualIncome: "বার্ষিক আয়",
    declaration: "ঘোষণা",
    signature: "স্বাক্ষর",
  },
  ta: {
    fullName: "முழுப் பெயர்",
    address1: "முகவரி வரி 1",
    address2: "முகவரி வரி 2",
    district: "மாவட்டம்",
    state: "மாநிலம்",
    pincode: "அஞ்சல் குறியீடு",
    dob: "பிறந்த தேதி",
    gender: "பாலினம்",
    phone: "தொலைபேசி எண்",
    email: "மின்னஞ்சல்",
    aadhaar: "ஆதார் எண்",
    pan: "பான் எண்",
    maritalStatus: "திருமண நிலை",
    occupation: "வேலை/தொழில்",
    annualIncome: "வருடாந்திர வருமானம்",
    declaration: "அறிக்கை",
    signature: "கையொப்பம்",
  },
  te: {
    fullName: "పూర్తి పేరు",
    address1: "చిరునామా వరుస 1",
    address2: "చిరునామా వరుస 2",
    district: "జిల్లా",
    state: "రాష్ట్రం",
    pincode: "పిన్ కోడ్",
    dob: "జనన తేది",
    gender: "లింగం",
    phone: "ఫోన్ నంబర్",
    email: "ఇమెయిల్",
    aadhaar: "ఆధార్ నంబర్",
    pan: "పాన్ నంబర్",
    maritalStatus: "వైవాహిక స్థితి",
    occupation: "ఉద్యోగం/వృత్తి",
    annualIncome: "వార్షిక ఆదాయం",
    declaration: "ప్రకటన",
    signature: "సంతకం",
  },
  mr: {
    fullName: "पूर्ण नाव",
    address1: "पत्ता ओळ 1",
    address2: "पत्ता ओळ 2",
    district: "जिल्हा",
    state: "राज्य",
    pincode: "पिन कोड",
    dob: "जन्मतारीख",
    gender: "लिंग",
    phone: "फोन नंबर",
    email: "ईमेल",
    aadhaar: "आधार क्रमांक",
    pan: "पॅन क्रमांक",
    maritalStatus: "वैवाहिक स्थिती",
    occupation: "व्यवसाय",
    annualIncome: "वार्षिक उत्पन्न",
    declaration: "घोषणा",
    signature: "स्वाक्षरी",
  },
  gu: {
    fullName: "પૂરું નામ",
    address1: "સરનામું લાઇન 1",
    address2: "સરનામું લાઇન 2",
    district: "જિલ્લો",
    state: "રાજ્ય",
    pincode: "પિન કોડ",
    dob: "જન્મ તારીખ",
    gender: "લિંગ",
    phone: "ફોન નંબર",
    email: "ઇમેઇલ",
    aadhaar: "આધાર નંਬਰ",
    pan: "પાન નંबर",
    maritalStatus: "વૈવાહિક સ્થિતિ",
    occupation: "વ્યવસાય",
    annualIncome: "વાર્ષિક આવક",
    declaration: "ઘોષણા",
    signature: "હસ્તાક્ષર",
  },
  kn: {
    fullName: "ಪೂರ್ಣ ಹೆಸರು",
    address1: "ವಿಳಾಸ ಸಾಲು 1",
    address2: "ವಿಳಾಸ ಸಾಲು 2",
    district: "ಜಿಲ್ಲೆ",
    state: "ರಾಜ್ಯ",
    pincode: "ಪಿನ್ ಕೋಡ್",
    dob: "ಜನ್ಮ ದಿನಾಂಕ",
    gender: "ಲಿಂಗ",
    phone: "ದೂರವಾಣಿ ಸಂಖ್ಯೆ",
    email: "ಇಮೇಲ್",
    aadhaar: "ಆಧಾರ್ ಸಂಖ್ಯೆ",
    pan: "ಪ್ಯಾನ್ ಸಂಖ್ಯೆ",
    maritalStatus: "ವೈವಾಹಿಕ ಸ್ಥಿತಿ",
    occupation: "ಉದ್ಯೋಗ/ವೃತ್ತಿ",
    annualIncome: "ವಾರ್ಷಿಕ ಆದಾಯ",
    declaration: "ಪ್ರಕಟಣೆ",
    signature: "ಸಹಿ",
  },
  ml: {
    fullName: "പൂർണ്ണ നാമം",
    address1: "വിലാസം വരി 1",
    address2: "വിലാസം വരി 2",
    district: "ജില്ല",
    state: "സംസ്ഥാനം",
    pincode: "പിൻ കോഡ്",
    dob: "ജനന തീയതി",
    gender: "ലിംഗം",
    phone: "ഫോൺ നമ്പർ",
    email: "ഇമെയിൽ",
    aadhaar: "ആധാർ നമ്പർ",
    pan: "പാൻ നമ്പർ",
    maritalStatus: "വൈവാഹിക സ്ഥിതി",
    occupation: "തൊഴിൽ",
    annualIncome: "വാർഷിക വരുമാനം",
    declaration: "പ്രഖ്യാപനം",
    signature: "സഹി",
  },
  pa: {
    fullName: "ਪੂਰਾ ਨਾਮ",
    address1: "ਪਤਾ ਲਾਈਨ 1",
    address2: "ਪਤਾ ਲਾਈਨ 2",
    district: "ਜ਼ਿਲ੍ਹਾ",
    state: "ਰਾਜ",
    pincode: "ਪਿਨ ਕੋਡ",
    dob: "ਜਨਮ ਤਾਰੀਖ",
    gender: "ਲਿੰਗ",
    phone: "ਫੋਨ ਨੰਬਰ",
    email: "ਈਮੇਲ",
    aadhaar: "ਆਧਾਰ ਨੰਬਰ",
    pan: "ਪੈਨ ਨੰਬਰ",
    maritalStatus: "ਵਿਵਾਹਿਕ ਦਰਜਾ",
    occupation: "ਪੇਸ਼ਾ",
    annualIncome: "ਸਲਾਨਾ ਆਮਦਨ",
    declaration: "ਘੋਸ਼ਣਾ",
    signature: "ਦਸਤਖਤ",
  },
  or: {
    fullName: "ପୂର୍ଣ୍ଣ ନାମ",
    address1: "ଠିକଣା ଲାଇନ୍ 1",
    address2: "ଠିକଣା ଲାଇନ୍ 2",
    district: "ଜିଲ୍ଲା",
    state: "ରାଜ୍ୟ",
    pincode: "ପିନ୍ କୋଡ୍",
    dob: "ଜନ୍ମ ତାରିଖ",
    gender: "ଲିଙ୍ଗ",
    phone: "ଫୋନ୍ ନମ୍ବର",
    email: "ଇମେଲ୍",
    aadhaar: "ଆଧାର ନମ୍ବର",
    pan: "ପାନ୍ ନମ୍ବର",
    maritalStatus: "ବିବାହିତ ସ୍ଥିତି",
    occupation: "ପେଶା",
    annualIncome: "ବାର୍ଷିକ ଆୟ",
    declaration: "ଘୋଷଣା",
    signature: "ସହି",
  },
  as: {
    fullName: "সম্পূৰ্ণ নাম",
    address1: "ঠিকনা শাৰী ১",
    address2: "ঠিকনা শাৰী ২",
    district: "জিলা",
    state: "ৰাজ্য",
    pincode: "পিন ক'ড",
    dob: "জন্ম তাৰিখ",
    gender: "লিংগ",
    phone: "ফোন নম্বৰ",
    email: "ইমেইল",
    aadhaar: "আধাৰ নম্বৰ",
    pan: "পেন নম্বৰ",
    maritalStatus: "বৈবাহিক স্থিতি",
    occupation: "পেচা",
    annualIncome: "বাৰ্ষিক আয়",
    declaration: "ঘোষণা",
    signature: "স্বাক্ষৰ",
  },
  ur: {
    fullName: "پورا نام",
    address1: "پتہ لائن 1",
    address2: "پتہ لائن 2",
    district: "ضلع",
    state: "ریاست",
    pincode: "پن کوڈ",
    dob: "تاریخ پیدائش",
    gender: "صنف",
    phone: "فون نمبر",
    email: "ای میل",
    aadhaar: "آدھار نمبر",
    pan: "پین نمبر",
    maritalStatus: "ازدواجی حیثیت",
    occupation: "پیشہ",
    annualIncome: "سالانہ آمدنی",
    declaration: "اعلان",
    signature: "دستخط",
  },
};

export const EXPLANATIONS: Record<LanguageCode, Dictionary> = {
  hi: {
    fullName: "अपने आधार/दस्तावेज़ के अनुसार पूरा नाम लिखें।",
    address1: "घर नंबर, गली/सड़क का नाम लिखें।",
    address2: "कॉलोनी/गांव, क्षेत्र का नाम लिखें (वैकल्पिक)।",
    district: "अपने ज़िले का नाम लिखें।",
    state: "अपने राज्य का नाम चुनें/लिखें।",
    pincode: "6 अंकों का पिन कोड लिखें।",
    dob: "दिन-महीना-वर्ष (DD/MM/YYYY) में लिख���ं।",
    gender: "पुरुष/महिला/अन्य चुनें।",
    phone: "10 अंकों का मोबाइल नंबर।",
    email: "जैसे example@mail.com",
    aadhaar: "12 अंकों की आधार संख्या।",
    pan: "10 अक्षरों का पैन (ABCDE1234F)।",
    maritalStatus: "अविवाहित/विवाहित/अन्य।",
    occupation: "आप क्या काम करते हैं।",
    annualIncome: "रुपयों में साल की आय।",
    declaration: "दिए गए विवरण सत्य होने की पुष्टि।",
    signature: "फॉर्म भरने वाले व्यक्ति के हस्ताक्षर।",
  },
  bn: {
    fullName: "আধার/দলিল অনুযায়ী আপনার সম্পূর্ণ নাম লিখুন।",
    address1: "বাড়ির নম্বর, রাস্তার নাম লিখুন।",
    address2: "এলাকা/পাড়া/গ্রামের নাম (ঐচ্ছিক)।",
    district: "আপনার জেলার নাম।",
    state: "আপনার রাজ্যের নাম।",
    pincode: "৬ সংখ্যার পিন কোড।",
    dob: "দিন/মাস/বছর (DD/MM/YYYY)।",
    gender: "পুরুষ/মহিলা/অন্যা��্য।",
    phone: "১০ সংখ্যার মোবাইল নম্বর।",
    email: "যেমন example@mail.com",
    aadhaar: "১২ সংখ্যার আধার নম্বর।",
    pan: "১০ অক্ষরের প্যান।",
    maritalStatus: "অবিবাহিত/বিবাহিত/অন্যান্য।",
    occupation: "আপনার পেশা।",
    annualIncome: "বছরে মোট আয়।",
    declaration: "প্রদত্ত তথ্য সত্য বলে ঘোষণা।",
    signature: "ফর্ম পূরণকারীর স্বাক্ষর।",
  },
  ta: {
    fullName: "ஆதார்/ஆவணப்படி முழுப் பெயரை எழுதுங்கள்.",
    address1: "வீட்டு எண், தெரு பெயர்.",
    address2: "பகுதி/கிராமம் (விருப்பம்).",
    district: "உங்கள் மாவட்டம்.",
    state: "உங்கள் மாநிலம்.",
    pincode: "6 இலக்க அஞ்சல் குறியீடு.",
    dob: "DD/MM/YYYY வடிவம்.",
    gender: "ஆண்/பெண்/மற்றவை.",
    phone: "10 இலக்க கைபேசி எண்.",
    email: "உதா. example@mail.com",
    aadhaar: "12 இலக்க ஆதார் எண்.",
    pan: "10 எழுத்து பான்.",
    maritalStatus: "திருமணமான/இல்லை/மற்றவை.",
    occupation: "நீங்கள் செய்யும் வேலை.",
    annualIncome: "வருடாந்திர வருமானம்.",
    declaration: "வழங்கிய தகவல் உண்மையென உறுதி.",
    signature: "கையொப்பம்.",
  },
  te: {
    fullName: "ఆధార్/డాక్యుమెంట్ ప్రకారం పూర్తి పేరు.",
    address1: "ఇంటి నెం., వీధి పేరు.",
    address2: "ప్రాంతం/గ్రామం (ఐచ్చికం).",
    district: "మీ జిల్లా.",
    state: "మీ రాష్ట్రం.",
    pincode: "6 అంకెల పిన్ కోడ్.",
    dob: "DD/MM/YYYY విధానం.",
    gender: "పురుషుడు/మహిళ/ఇతరులు.",
    phone: "10 అంకెల మొబైల్ నంబర్.",
    email: "ఉదా. example@mail.com",
    aadhaar: "12 అంకెల ఆధార్ నంబర్.",
    pan: "10 అక్షరాల పాన్.",
    maritalStatus: "వివాహిత/అవివాహిత/ఇతరులు.",
    occupation: "మీ ఉద్యోగం.",
    annualIncome: "ఏడాది ఆదాయం.",
    declaration: "ఇచ్చిన వివరాలు నిజమని ధృవీకరణ.",
    signature: "సంతకం.",
  },
  mr: {
    fullName: "आधार/दस्तऐवजानुसार पूर्ण नाव.",
    address1: "घर क्रमांक, रस्ता नाव.",
    address2: "भाग/गाव (ऐच्छिक).",
    district: "तुमचा जिल्हा.",
    state: "तुमचे राज्य.",
    pincode: "6 अंकी पिन कोड.",
    dob: "DD/MM/YYYY स्वरूप.",
    gender: "पुरुष/महिला/इतर.",
    phone: "10 अंकी मोबाइल नंबर.",
    email: "उदा. example@mail.com",
    aadhaar: "12 अंकी आधार क्रमांक.",
    pan: "10 अक्षरी पॅन.",
    maritalStatus: "अविवाहित/विवाहित/इतर.",
    occupation: "तुमचा व्यवसाय.",
    annualIncome: "वार्षिक उत्पन्न.",
    declaration: "दिलेली माहिती खरी असल्याची खात्री.",
    signature: "स्वाक्षरी.",
  },
  gu: {
    fullName: "આધાર/દસ્તાવેજ મુજબ પૂરું નામ.",
    address1: "મકાન નંબર, રસ્તા નું નામ.",
    address2: "વિસ્તાર/ગામ (વૈકલ્પિક).",
    district: "તમારો જિલ્લો.",
    state: "તમારું રાજ્ય.",
    pincode: "6 અંક નો પિન કોડ.",
    dob: "DD/MM/YYYY ફોર્મેટ.",
    gender: "પુરુષ/મહిళા/અન્ય.",
    phone: "10 અંકનો મોબાઇલ નંબર.",
    email: "ઉદાહરણ: example@mail.com",
    aadhaar: "12 અંકનો આધાર નંબર.",
    pan: "10 અક્ષરનો પાન.",
    maritalStatus: "અવિવાહિત/વિવાહિત/અન્ય.",
    occupation: "તમારો વ્યવસાય.",
    annualIncome: "વર્ષિક આવક.",
    declaration: "આપેલી માહિતી સાચી હોવાની ખાતરી.",
    signature: "હસ્તાક્ષર.",
  },
  kn: {
    fullName: "ಆಧಾರ್/ದಾಖಲೆ ಪ್ರಕಾರ ಪೂರ್ಣ ಹೆಸರು.",
    address1: "ಮನೆ ಸಂ., ರಸ್ತೆ ಹೆಸರು.",
    address2: "ಪ್ರದೇಶ/ಗ್ರಾಮ (ಐಚ್ಛಿಕ).",
    district: "ನಿಮ್ಮ ಜಿಲ್ಲೆ.",
    state: "ನಿಮ್ಮ ರಾಜ್ಯ.",
    pincode: "6 ಅಂಕೆಯ ಪಿನ್ ಕೋಡ್.",
    dob: "DD/MM/YYYY ಶೈಲಿ.",
    gender: "ಪುರುಷ/ಸ್ತ್ರೀ/ಇತರೆ.",
    phone: "10 ಅಂಕೆಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ.",
    email: "ಉದಾ. example@mail.com",
    aadhaar: "12 ಅಂಕೆಯ ಆಧಾರ್ ಸಂಖ್ಯೆ.",
    pan: "10 ಅಕ್ಷರದ ಪ್ಯಾನ್.",
    maritalStatus: "ಅವಿವಾಹಿತ/ವಿವಾಹಿತ/ಇತರೆ.",
    occupation: "ನಿಮ್ಮ ಉದ್ಯೋಗ.",
    annualIncome: "ವಾರ್ಷಿಕ ಆದಾಯ.",
    declaration: "ನೀಡಿದ ಮಾಹಿತಿ ನಿಜವೆಂದು ದೃಢೀಕರಣ.",
    signature: "ಸಹಿ.",
  },
  ml: {
    fullName: "ആധാർ/രേഖ പ്രകാരം പൂർണ്ണ നാമം.",
    address1: "വീട് നമ്പർ, വീഥി പേര്.",
    address2: "പ്രദേശം/ഗ്രാം (ഐച്ഛികം).",
    district: "നിങ്ങളുടെ ജില്ല.",
    state: "നിങ്ങളുടെ സംസ്ഥാനം.",
    pincode: "6 അക്ക പിൻ കോഡ്.",
    dob: "DD/MM/YYYY ഫോർമാറ്റ്.",
    gender: "പുരുഷൻ/സ്ത്രീ/മറ്റുള്ളവർ.",
    phone: "10 അക്ക മൊബൈൽ നമ്പർ.",
    email: "ഉദാ. example@mail.com",
    aadhaar: "12 അക്ക ആധാർ നമ്പർ.",
    pan: "10 അക്ക പാൻ.",
    maritalStatus: "അവിവാഹിത/വിവാഹിത/മറ്റുള്ളവർ.",
    occupation: "താങ്കളുടെ തൊഴിൽ.",
    annualIncome: "വാർഷിക വരുമാനം.",
    declaration: "നൽകിയ വിവരം ശരിയെന്ന് ഉറപ്പ്.",
    signature: "സഹി.",
  },
  pa: {
    fullName: "ਆਧਾਰ/ਦਸਤਾਵੇਜ਼ ਅਨੁਸਾਰ ਪੂਰਾ ਨਾਮ.",
    address1: "ਘਰ ਨੰਬਰ, ਗਲੀ/ਸੜਕ ਦਾ ਨਾਮ.",
    address2: "ਇਲਾਕਾ/ਪਿੰਡ (ਚੋਣੀ).",
    district: "ਤੁਹਾਡਾ ਜ਼ਿਲ੍ਹਾ.",
    state: "ਤੁਹਾਡੀ ਰਾਜ.",
    pincode: "6 ਅੰਕਾਂ ਦਾ ਪਿਨ ਕੋਡ.",
    dob: "DD/MM/YYYY ਫਾਰਮੈਟ.",
    gender: "ਪੁਰਸ਼/ਇਸਤਰੀ/ਹੋਰ.",
    phone: "10 ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ.",
    email: "ਜਿਵੇਂ example@mail.com",
    aadhaar: "12 ਅੰਕਾਂ ਦਾ ਆਧਾਰ ਨੰਬਰ.",
    pan: "10 ਅੱਖਰਾਂ ਦਾ ਪੈਨ.",
    maritalStatus: "ਅਵਿਵਾਹਿਤ/ਵਿਵਾਹਿਤ/ਹੋਰ.",
    occupation: "ਤੁਹਾਡਾ ਪੇਸ਼ਾ.",
    annualIncome: "ਸਲਾਨਾ ਆਮਦਨ.",
    declaration: "ਦਿੱਤੀ ਜਾਣਕਾਰੀ ਸਹੀ ਹੋਣ ਦੀ ਪੁਸ਼ਟੀ.",
    signature: "ਦਸਤਖਤ.",
  },
  or: {
    fullName: "ଆଧାର/ଦଳିଲଅନୁଯାୟୀ ପୂର୍ଣ୍ଣ ନାମ.",
    address1: "ବାଡ଼ି ନମ୍ବର, ରାସ୍ତାର ନାମ.",
    address2: "ଅଞ୍ଚଳ/ଗ୍ରାମ (ଇଚ୍ଛାନୁସାରେ).",
    district: "ଆପଣଙ୍କ ଜିଲ୍ଲା.",
    state: "ଆପଣଙ୍କ ରାଜ୍ୟ.",
    pincode: "6 ଅଙ୍କର ପିନ କୋଡ୍.",
    dob: "DD/MM/YYYY ଫର୍ମାଟ୍.",
    gender: "ପୁରୁଷ/��ହିଳା/ଅନ୍ୟ.",
    phone: "10 ଅଙ୍କର ମୋବାଇଲ୍ ନମ୍ବର.",
    email: "ଯଥା example@mail.com",
    aadhaar: "12 ଅଙ୍କର ଆଧାର ନମ୍ବର.",
    pan: "10 ଅକ୍ଷରର ପାନ୍.",
    maritalStatus: "ଅବିବାହିତ/ବିବାହିତ/ଅନ୍ୟ.",
    occupation: "ଆପଣଙ୍କ ବ୍ୟବସାୟ/କାମ.",
    annualIncome: "ବାର୍ଷିକ ଆୟ.",
    declaration: "ଦିଆଯାଇଥିବା ସତ୍ୟ ତଥ୍ୟର ନିଶ୍ଚୟତା.",
    signature: "ସହି.",
  },
  as: {
    fullName: "আধাৰ/দলিল অনুসৰি সম্পূৰ্ণ নাম.",
    address1: "ঘৰ নং, ৰাস্তা নাম.",
    address2: "এলাকা/গাঁও (বিকল্প).",
    district: "আপোনাৰ জিলা.",
    state: "আপোনাৰ ৰাজ্য.",
    pincode: "৬ সংখ্যাৰ পিন ক'ড.",
    dob: "DD/MM/YYYY ফৰ্মেট.",
    gender: "পুৰুষ/স্ত্ৰী/অন্য.",
    phone: "১০ সংখ্যাৰ ম'বাইল নম্বৰ.",
    email: "যেনে example@mail.com",
    aadhaar: "১২ সংখ্যাৰ আধাৰ ��ম্বৰ.",
    pan: "১০ আখৰৰ পেন.",
    maritalStatus: "অবিবাহিত/বিবাহিত/অন্য.",
    occupation: "আপোনাৰ পেচা.",
    annualIncome: "বাৰ্ষিক আয়.",
    declaration: "দিয়া তথ্য সত্য বুলি নিশ্চিতকৰণ.",
    signature: "স্বাক্ষৰ.",
  },
  ur: {
    fullName: "آدھار/دستاویز کے مطابق پورا نام.",
    address1: "مکان نمبر، سڑک کا نام.",
    address2: "علاقہ/گاؤں (اختیاری).",
    district: "آپ کا ضلع.",
    state: "آپ کی ریاست.",
    pincode: "6 ہندسوں کا پن کوڈ.",
    dob: "DD/MM/YYYY فارمیٹ.",
    gender: "مرد/خاتون/دیگر.",
    phone: "10 ہندسوں کا موبائل نمبر.",
    email: "مثلاً example@mail.com",
    aadhaar: "12 ہندسوں کا آدھار نمبر.",
    pan: "10 حروف کا پین.",
    maritalStatus: "غیر شادی شدہ/شادی شدہ/دیگر.",
    occupation: "آپ کا پیشہ.",
    annualIncome: "سالانہ آمدنی.",
    declaration: "دی گئی معلومات کے درست ہونے کی تصدیق.",
    signature: "دستخط.",
  },
};

export function translateLabel(key: FieldKey, lang: LanguageCode): string {
  const dict = LABELS[lang];
  return dict?.[key] ?? EN_LABELS[key];
}

export function explainField(key: FieldKey, lang: LanguageCode): string | undefined {
  return EXPLANATIONS[lang]?.[key];
}
